# general settings
name: train_MPRNet_DIV2K_LMDB_G1
model_type: QEModel
scale: 1
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0
reproduce: True

# dataset and data loader settings
datasets:
  train:
    name: DIV2K
    type: PairedImageDataset
#    dataroot_gt: datasets/DIV2K/train
#    dataroot_lq: datasets/DIV2K/train_BPG_QP37
#    io_backend:
#      type: disk
    dataroot_gt: datasets/DIV2K/train_size128_step64_thresh0.lmdb
    dataroot_lq: datasets/DIV2K/train_BPG_QP37_size128_step64_thresh0.lmdb
    io_backend:
      type: lmdb

    gt_size: 128  # in accord with LMDB
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 16
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: DIV2K
    type: PairedImageDataset
    dataroot_gt: datasets/DIV2K/valid
    dataroot_lq: datasets/DIV2K/valid_BPG_QP37
    io_backend:
      type: disk

# network structures
network_g:
  type: MPRNet
  io_channels: 3
  n_feat: 16
  scale_unetfeats: 16
  scale_orsnetfeats: 16
  num_cab: 4

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [500000]
    restart_weights: [1]
    eta_min: !!float 1e-7

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e4
  save_img: false

  metrics:
    psnr:
      type: pyiqa

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true

# dist training settings
dist_params:
  backend: nccl
  port: 29500
